name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: make tidy

      - name: Linting
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12

      - name: Formatting
        run: make fmt

      - name: Build
        run: make build

      - name: Testing
        run: make test
